Applications/routes/web.php
<?php

Route::get('/', function () {
    return redirect()->route('reseller.shop.get');
});

/* --------- RESELLERS --------- */

// SHOP
Route::get('/', 'Resellers\ShopController@index')->name('reseller.shop.get');
Route::get('/shop', 'Resellers\ShopController@index')->name('reseller.shop.get');
Route::get('/shop/product/{id}', 'Resellers\ShopController@show')->name('reseller.shop.show.get');
Route::get('/shop/search', 'Resellers\ShopController@search')->name('reseller.shop.search.get');
Route::get('/shop/sort', 'Resellers\ShopController@sort')->name('reseller.shop.sort.get');

// AUTH
Route::group(['prefix' => 'reseller', 'middleware' => ['guest']], function () {
    Route::get('/login', 'Resellers\Auth\AuthController@getLogin')->name('reseller.login.get');
	Route::post('/login', 'Resellers\Auth\AuthController@postLogin')->name('reseller.login.post');

	Route::get('/register', 'Resellers\Auth\AuthController@getRegister')->name('reseller.register.get');
	Route::post('/register', 'Resellers\Auth\AuthController@postRegister')->name('reseller.register.post');
});


Route::group(['prefix' => 'reseller'], function() {
	// LOGOUT
	Route::get('/logout', 'Resellers\Auth\AuthController@logout')->name('reseller.logout.get');

	// DASHBOARD
	Route::get('/dashboard', 'Resellers\DashboardController@index')->name('reseller.dashboard.get');

	// ORDERS
	Route::get('/orders', 'Resellers\OrderController@index')->name('reseller.order.get');

	// ADDRESS BILLING
	Route::get('/address/billing', 'Resellers\AddressBillingController@index')->name('reseller.address.billing.get');
	Route::put('/address/billing', 'Resellers\AddressBillingController@update')->name('reseller.address.billing.update');

	// ADDRESS SHIPPING
	Route::get('/address/shipping', 'Resellers\AddressShippingController@index')->name('reseller.address.shipping.get');
	Route::put('/address/shipping', 'Resellers\AddressShippingController@update')->name('reseller.address.shipping.update');

	// DETAIL ACCOUNT
	Route::get('/profile', 'Resellers\ProfileController@index')->name('reseller.profile.get');
	Route::put('/profile', 'Resellers\ProfileController@update')->name('reseller.profile.update');
	Route::put('/profile/change-password', 'Resellers\ProfileController@changePassword')->name('reseller.profile.change.password.update');

	// CART
	Route::post('/cart', 'Resellers\CartController@store')->name('reseller.cart.post');
	Route::post('/cart/delete', 'Resellers\CartController@delete')->name('reseller.cart.delete');

	// CHECKOUT
	Route::get('/checkout', 'Resellers\CheckoutController@index')->name('reseller.checkout.get');
	Route::post('/checkout', 'Resellers\CheckoutController@store')->name('reseller.checkout.post');
	Route::get('/checkout/order-received/{id}', 'Resellers\CheckoutController@orderReceived')->name('reseller.orderReceived.get');
	Route::get('/checkout/konfirmasi-pembayaran/{id}', 'Resellers\CheckoutController@konfirmasiPembayaran')->name('reseller.konfirmasiPembayaran.get');
	Route::post('/checkout/konfirmasi-pembayaran/{id}', 'Resellers\CheckoutController@konfirmasiPembayaranPost')->name('reseller.konfirmasiPembayaran.post');
});


/* --------- ADMIN --------- */
Route::group(['prefix' => 'admin', 'namespace' => 'Auth'], function() {
	// Authentication Routes
	Route::get('/', function () {
		return redirect('admin/login');
	});
	Route::get('/login', 'LoginController@showLoginForm')->name('login');
	Route::post('/login', 'LoginController@login');
	Route::post('/logout', 'LoginController@logout')->name('logout');

	// Registration Routes...
	Route::get('/register', 'RegisterController@showRegistrationForm')->name('register');
	Route::post('/register', 'RegisterController@register');
});

Route::group(['prefix'=>'admin', 'middleware'=> ['auth', 'admin']], function() {
	
	/* --------- Dashboard --------- */
	Route::get('/home', 'HomeController@index')->name('home');

	/* --------- Order / Transaction --------- */
	Route::resource('/order', 'OrderController')->except([
		'show', 'create', 'edit'
	]);
	Route::get('/order/detail/{id}', 'OrderController@show')->name('order.detail');
	Route::get('/order/search', 'OrderController@search')->name('order.search');
	Route::get('/order/new_order', 'OrderController@create')->name('order.new_order');
	Route::get('/order/edit_order/{id}', 'OrderController@edit')->name('order.edit_order');
	Route::get('/order/canceled', 'OrderController@canceled')->name('order.canceled');

	/* --------- Product Management --------- */
	Route::resource('/product', 'ProductController')->except([
		'show', 'create', 'edit'
	]);

	Route::get('/product/detail_product/{id}', 'ProductController@show')->name('product.detail');
	Route::get('/product/add_product', 'ProductController@create')->name('product.create');
	Route::get('/product/{id}/edit_product', 'ProductController@edit')->name('product.edit');
	Route::get('/product/search', 'ProductController@search')->name('product.search');
	Route::get('/product/history/{variant_id}', 'ProductController@history_variant')->name('product.history_variant');
	
	Route::get('/product/category', 'ProductCategoryController@index')->name('product_category.index');
	Route::get('/product/category/{slug}', 'ProductCategoryController@show')->name('product_category.detail');
	Route::get('/product/category/{id}/edit', 'ProductCategoryController@edit')->name('product_category.edit');
	Route::post('/product/category/store', 'ProductCategoryController@store')->name('product_category.store');
	Route::put('/product/category/{id}', 'ProductCategoryController@update')->name('product_category.update');
	Route::delete('/product/category/{id}', 'ProductCategoryController@destroy')->name('product_category.destroy');
	
	Route::get('/product/stock/listdata', 'ProductStockController@listData')->name('product_stock.data');
	Route::get('/product/stock', 'ProductStockController@index')->name('product_stock.index');
	Route::post('/product/stock', 'ProductStockController@store')->name('product_stock.store');
	Route::put('/product/stock/{id}', 'ProductStockController@update')->name('product_stock.update');
	Route::get('/product/stock/{id}/edit', 'ProductStockController@edit')->name('product_stock.edit');
	Route::delete('/product/stock/{id}', 'ProductStockController@destroy')->name('product_stock.destroy');

	Route::get('/product/attribute/listdata', 'ProductAttributeController@listData')->name('product_attribute.data');
	Route::get('/product/attribute', 'ProductAttributeController@index')->name('product_attribute.index');
	Route::post('/product/attribute', 'ProductAttributeController@store')->name('product_attribute.store');
	Route::put('/product/attribute/{id}', 'ProductAttributeController@update')->name('product_attribute.update');
	Route::get('/product/attribute/{id}/edit', 'ProductAttributeController@edit')->name('product_attribute.edit');
	Route::delete('/product/attribute/{id}', 'ProductAttributeController@destroy')->name('product_attribute.destroy');

	/* --------- Customer --------- */
	Route::get('/customer/listdata', 'CustomerController@listData')->name('customer.data');
	Route::resource('/customer', 'CustomerController')->except([
		'show', 'create'
	]);
	Route::get('/customer/search', 'CustomerController@searchCustomer')->name('customer.search');
	// Route::get('/customer/transaction/{id}', 'TransactionController@showCustomerTransaction')->name('customer.transaction');

	/* --------- Supplier --------- */
	Route::get('/supplier/listdata', 'SupplierController@listData')->name('supplier.data');
	Route::resource('/supplier', 'SupplierController')->except([
		'show', 'create'
	]);

	Route::get('/reseller', function() {
	    return 'View Not Found!';
	});

	/* --------- Expense --------- */
	Route::get('/expense/listdata', 'ExpenseController@listdata')->name('expense.data');
	Route::resource('/expense', 'ExpenseController')->except([
		'create'
	]);
	Route::get('/expense/search', 'ExpenseController@search')->name('expense.search');

	/* --------- Report --------- */
	Route::get('/report', 'ReportController@index')->name('report.index');
	Route::get('/report/search', 'ReportController@search')->name('report.search');
	Route::get('/report/detail/{id}', 'ReportController@show')->name('report.detail');

	/* --------- Analyzer --------- */
	Route::get('/analyzer', 'AnalyzerController@index')->name('analyzer.index');
	Route::get('/analyzer/best_seller', 'AnalyzerController@bestSeller')->name('analyzer.best_seller');
	Route::get('/analyzer/best_customer', 'AnalyzerController@bestCustomer')->name('analyzer.best_customer');
	Route::get('/analyzer/best_location', 'AnalyzerController@bestLocation')->name('analyzer.best_location');

	/* --------- Setting --------- */
	Route::get('/setting/general', 'SettingController@index')->name('setting.general');
	Route::get('/setting/supplier', 'SettingController@supplier')->name('setting.supplier');
	Route::get('/setting/user', 'SettingController@user')->name('setting.user');
	Route::get('/setting/sale_target', 'SettingController@saleTarget')->name('setting.sale_target');

	/* --------- Outlet --------- */
	Route::get('setting/general/outlet/{id}/edit', 'OutletController@edit')->name('outlet.edit');
	Route::post('setting/general/outlet', 'OutletController@insert')->name('outlet.insert');
	
	/* --------- User --------- */
	Route::resource('/role', 'RoleController')->except([
        'create', 'show'
    ]);

	/* --------- User --------- */
	Route::get('/user/listdata', 'UserController@listData')->name('user.data');
	Route::resource('/user', 'UserController')->except([
		'index', 'show'
	]);
	Route::get('/user/user_profile', 'UserController@profile')->name('user.profile');
	Route::put('/user/user_profile/{id}', 'UserController@changeProfile')->name('user.update_profile');

	Route::get('/user/roles/{id}', 'UserController@roles')->name('user.roles');
    Route::put('/user/roles/{id}', 'UserController@setRole')->name('user.set_role');

Applications/app/Product.php
<?php

namespace App;

use App\Model;

class Product extends Model
{

    public function product_stocks()
    {
        return $this->hasMany(Product_stock::class);
    }

    public function product_stock()
    {
        return $this->hasOne(Product_stock::class);
    }

    public function product_attributes()
    {
    	return $this->hasMany(Product_attribute::class);
    }

    public function product_categories()
    {
        return $this->belongsToMany(Product_category::class)->withTimestamps();
    }
}

Applications/resources/views/products/history.blade.php
@extends('layouts.master')

@section('title', 'Produk')

@push('css')
    <style>
        .form-control.fc_md, .btn_md { 
            padding: 0.5rem 1rem;
            font-size: 1rem;
            line-height: 1;
        }
    </style>
@endpush

@section('breadcrumb')
    @parent
    <li class="breadcrumb-item"><a href="{{ url('/products') }}">Produk</a></li>
    <li class="breadcrumb-item active">Histori</li>
@endsection

@section('main-content')
<div class="row">
    <div class="col-lg-12">
        @card
            
            <div class="row">
                <div class="col-md-4">
                    <p class="text-muted text-sm">HISTORI STOK</p>
                    <h1>Celana 
                        <small class="bg-light text-sm rounded border p-1">L, Blue Dark</small>
                    </h1>
                </div>

                <div class="col-md-8">
                    <form class="form-inline mt-lg-5 mt-md-5 float-right">
                        <input type="text" class="form-control fc_md mx-sm-2 my-2 my-md-0 my-lg-0 datepicker" name="from_date" id="from_date" placeholder="Dari Tanggal">
                        <input type="text" class="form-control fc_md mx-sm-2 my-2 my-md-0 my-lg-0 datepicker" name="to_date" id="to_date" placeholder="Sampai Tanggal">
                        <button class="btn btn-default px-3 btn-md"><i class="fas fa-search"></i></button>
                    </form>
                </div>

                <div class="col-md-12 table-responsive mt-3">
                    <table class="table table-sm table-bordered">
                        <thead class="thead-light">
                            <th class="text-center" width="3%">No</th>
                            <th>Tanggal Pesan</th>
                            <th>Keterangan</th>
                            <th class="text-center">Masuk</th>
                            <th class="text-center">Keluar</th>
                            <th class="text-center">Sisa Stok</th>
                        </thead>

                        <tbody>
                            @for ($i = 0; $i < 3; $i++)
                                <tr>
                                    <td class="text-center">{{ $i+1 }}</td>
                                    <td>
                                        Sabtu, 26 Oktober 2019 
                                        <span class="d-block text-muted text-sm">Diinputkan 1 jam yang lalu.</span>
                                    </td>
                                    <td>Stok Awal</td>
                                    <td class="text-success font-weight-bold text-center">20</td>
                                    <td class="text-danger font-weight-bold text-center">-</td>
                                    <td class="text-center font-weight-bold">20</td>
                                </tr>
                            @endfor
                        </tbody>
                    </table>
                </div>
            </div>
            
            @slot('footer')
                <a href="{{ route('product.index') }}" class="btn btn-md btn-orange">Kembali</a>
            @endslot
        @endcard
    </div>
</div>
@include('components.sweet')
@endsection


@push('scripts')
<script>
    $('.datepicker').datepicker()

    $('.table').DataTable({
        paginate: false,
        searching: false,
        bInfo: false,
    })
</script>
@endpush

Applications/resources/views/products/index.blade.php
@extends('layouts.master')

@section('title', 'Produk')

@push('css')
    <style>
        .custom-control-label {
            cursor: pointer;
        }
    </style>
@endpush

@section('breadcrumb')
    @parent
    <li class="breadcrumb-item active">Produk</li>
@endsection

@section('main-content')
<div class="row">

    <div class="col-md-6 col-12">
        <div class="form-group row">
            <div class="col-4">
                <select name="product_category" id="product_category" class="custom-select custom-select-sm">
                    <option value="all_categories">Semua Kategori</option>

                    @foreach ($product_categories as $category)
                        <option value="{{ strtolower($category->name) }}">{{ $category->name }}</option>
                    @endforeach

                    <option value="uncategorized">Uncategorized</option>
                    <option value="archived">Archived</option>
                </select>
            </div>
            
            <div class="col-6">
                <input type="text" class="form-control" name="product_name" id="product_name" placeholder="Masukan Nama produk">
            </div>
            
            <div class="col-2">
                <button class="btn btn-outline-primary">Filter</button>
            </div>
        </div>
    </div>
    
    <div class="col-md-4 col-12"></div>
    <div class="col-md-2 col-12">
        <div class="form-group">
            <select name="sort_by" id="sort_by" class="custom-select custom-select-sm">
                <option value="latest">Produk Terbaru</option>
                <option value="oldest">Produk Terlama</option>
                <option value="a_to_z">Urutkan A-Z</option>
                <option value="z_to_a">Urutkan Z-A</option>
                <option value="lowest">Harga Termurah - Termahal</option>
                <option value="most_expensive">Harga Termahal - Termurah</option>
                <option value="smallest">Stok Paling Sedikit</option>
                <option value="biggest">Stok Paling Banyak</option>
            </select>
        </div>
    </div>
    
    <div class="col-md-12">
        <div class="card mt-3 card-orange card-outline">
            <div class="card-header">
                <a href="{{ route('product.create') }}" class="btn btn-primary"><i class="fas fa-plus-circle"></i> Tambah</a>
                <a href="#" class="btn btn-danger"><i class="fas fa-trash-alt"></i> Hapus</a>
                <a href="{{ route('product.index') }}" class="btn btn-primary"><i class="fas fa-sync"></i> Refresh</a>
                <a onclick="exportPDF()" href="#" class="btn btn-sm btn-default"><i class="fas fa-file-pdf"></i> Export PDF</a>
                <a onclick="exportExcel()" href="#" class="btn btn-sm btn-default"><i class="fas fa-file-excel"></i> Export Excel</a>
                <a onclick="importExcel()" href="#" class="btn btn-sm btn-default"><i class="fas fa-file-excel"></i> Import Excel</a>
            </div>

            <div class="card-body table-responsive">
                @table
                    @slot('thead')
                        <th width="3%">
                            <div class="custom-control custom-checkbox" style="margin-right: -1rem;">
                                <input type="checkbox" class="custom-control-input" id="select-all">
                                <label class="custom-control-label" for="select-all"></label>
                            </div>
                        </th>
                        <th class="text-center" width="10%"><i class="fas fa-image"></i></th>
                        <th>Nama</th>
                        <th>SKU</th>
                        <th>Stok</th>
                        <th>Harga</th>
                        <th>Kategori</th>
                        <th>Tanggal</th>
                    @endslot
                        
                    <body>
                        
                        @if (isset($slug))
                            @foreach ($products->products as $key => $product)
                            <tr>
                                <td>
                                    <div class="custom-control custom-checkbox">
                                        <input type="checkbox" class="custom-control-input" id="customCheck{{ $key+1 }}">
                                        <label class="custom-control-label" for="customCheck{{ $key+1 }}"></label>
                                    </div>
                                </td>
                                <td class="text-center">
                                    @if ($product->photo)
                                        <img src="{{ Storage::disk('public')->url('uploads/products/'. $product->photo) }}" alt="{{ $product->photo }}" width="50" class="rounded m-1">
                                    @else
                                        <img src="https://via.placeholder.com/50.png" alt="img-product" width="50" class="rounded m-1">
                                    @endif
                                </td>
                                <td class="name_product">
                                    <a href="{{ route('product.detail', $product->id) }}" class="font-weight-bold text-uppercase">{{ $product->name }}</a>

                                    <div class="d-none more-action">
                                        <a href="{{ route('product.detail', $product->id) }}" class="btn btn-link text-secondary" title="Lihat"><i class="fa fa-eye"></i></a>
                                        <a href="{{ route('product.edit', $product->id) }}" class="btn btn-link text-secondary" title="Edit"><i class="fa fa-pencil-alt"></i></a>
                                        <form action="{{ route('product.destroy', $product->id) }}" method="post" class="d-inline-block">
                                            @csrf @method('delete')
                                            <button class="btn btn-link text-danger" onclick="return confirm('Are you sure?')" title="Hapus"><i class="fa fa-trash-alt"></i></button>
                                        </form>
                                    </div>
                                </td>
                                <td>{{ !empty($product->sku) ? $product->sku : '-' }}</td>
                                <td><span class="text-success"></span>{{ $product->amount }}</td>
                                <td>{{ format_uang($product->salling_price) }}</td>
                                <td>
                                    @foreach ($product->product_categories as $category_product)
                                        <a href="{{ route('product_category.detail', $category_product->slug) }}" class="badge badge-primary">{{ $category_product->name }}</a>
                                    @endforeach
                                </td>
                                <td title="{{ !empty($product->created_at) ? tanggal_indonesia($product->created_at) : '-' }}">
                                    {{ !empty($product->created_at) ? date('d/m/Y', strtotime($product->created_at)) : '-' }}
                                </td>
                            </tr>
                            @endforeach
                        @else                        
                            @foreach ($products as $key => $product)
                            <tr>
                                <td>
                                    <div class="custom-control custom-checkbox">
                                        <input type="checkbox" class="custom-control-input" id="customCheck{{ $key+1 }}">
                                        <label class="custom-control-label" for="customCheck{{ $key+1 }}"></label>
                                    </div>
                                </td>
                                <td class="text-center">
                                    @if ($product->photo)
                                        <img src="{{ Storage::disk('public')->url('uploads/products/'. $product->photo) }}" alt="{{ $product->photo }}" width="50" class="rounded m-1">
                                    @else
                                        <img src="https://via.placeholder.com/50.png" alt="img-product" width="50" class="rounded m-1">
                                    @endif
                                </td>
                                <td class="name_product">
                                    <a href="{{ route('product.detail', $product->id) }}" class="font-weight-bold text-uppercase">{{ $product->name }}</a>

                                    <div class="d-none more-action">
                                        <a href="{{ route('product.detail', $product->id) }}" class="btn btn-link text-secondary" title="Lihat"><i class="fa fa-eye"></i></a>
                                        <a href="{{ route('product.edit', $product->id) }}" class="btn btn-link text-secondary" title="Edit"><i class="fa fa-pencil-alt"></i></a>
                                        <form action="{{ route('product.destroy', $product->id) }}" method="post" class="d-inline-block">
                                            @csrf @method('delete')
                                            <button class="btn btn-link text-danger" onclick="return confirm('Are you sure?')" title="Hapus"><i class="fa fa-trash-alt"></i></button>
                                        </form>
                                    </div>
                                </td>
                                <td>{{ !empty($product->sku) ? $product->sku : '-' }}</td>
                                <td><span class="text-success"></span>{{ $product->amount }}</td>
                                <td>{{ format_uang($product->salling_price) }}</td>
                                <td>
                                    @foreach ($product->product_categories as $category_product)
                                        <a href="{{ route('product_category.detail', $category_product->slug) }}" class="badge badge-primary">{{ $category_product->name }}</a>
                                    @endforeach
                                </td>
                                <td title="{{ !empty($product->created_at) ? tanggal_indonesia($product->created_at) : '-' }}">
                                    {{ !empty($product->created_at) ? date('d/m/Y', strtotime($product->created_at)) : '-' }}
                                </td>
                            </tr>
                            @endforeach
                        @endif
                    </body>
                @endtable
            </div>
        </div>            
            
        {{-- @if($products->count() >= 10)
            <div class="mt-3 float-right">
                {{ $products->links() }}
            </div>                
        @endif --}}
    </div>
</div>
@include('components.sweet')
@endsection


@push('scripts')
<script>
    let table = $('.table').DataTable({
        'autoWidth': false,
        "language": {
          "emptyTable": "Ups data masih kosong!.",
          "zeroRecords": "Ups data tidak ditemukan!."
        },
        "lengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
        "pageLength": 100
    })

    $('#select-all').click(function() {
        $(':checkbox').prop('checked', this.checked);
    })
    
    $('.name_product').each(function (e) {
        $(this).hover(function () {
            $(this).children().eq(1).toggleClass('d-none')
        })
    })

</script>
@endpush

Applications/resources/views/products/show.blade.php
@extends('layouts.master')

@section('title', 'Produk')

@push('css')
    <link href="https://unpkg.com/ionicons@4.5.10-0/dist/css/ionicons.min.css" rel="stylesheet">
    <style>
        .table td {
            border-bottom: 0;
        }

        .small td {
            font-size: .9em;
        }

        @media (min-width: 575.98px) {
            .table.grosir {
                width: 50%;
            }

            .side-right {
                border-right: 1px solid rgba(0, 0, 0, 0.125);
            }
        }
    </style>
@endpush

@section('breadcrumb')
    @parent
    <li class="breadcrumb-item"><a href="{{ url('/products') }}">Produk</a></li>
    <li class="breadcrumb-item active">Detail</li>
@endsection

@section('main-content')
<div class="row">
    <div class="col-lg-12">
        @card
            
            <div class="row">
                <div class="col-md-6 side-right">
                    <h1>Celana 
                        <small class="bg-success text-sm rounded-pill p-1 text-uppercase">Grosir</small>
                    </h1>
                    <p class="text-muted mt-3">Nyaman digunakan untuk bersantai & bekerja</p>
                </div>

                <div class="col-md-6 pl-3">
                    <a href="{{ route('product.edit', 1) }}" class="btn btn-default btn-md float-right"><i class="fas fa-edit"></i> Edit</a>
                    
                    <span class="d-block text-muted text-sm">JENIS PRODUK</span>
                    <span class="d-block font-weight-bold">{{ __('Stock Sendiri') }}</span>
                    <br>

                    <span class="d-block text-muted text-sm">KATEGORI</span>
                    <span class="d-block font-weight-bold">{{ __('Tshirt') }}</span>
                    <br>

                    <span class="d-block text-muted text-sm">TOTAL STOK</span>
                    <span class="d-block font-weight-bold">{{ __('29') }}</span>
                    <br>
                </div>

                <div class="col-md-12 table-responsive">
                    <table class="table table-hover mt-3">
                        <tr class="small">
                            <td rowspan="2" width="10%" style="padding: 0; border: 0;">
                                <img src="https://via.placeholder.com/100.png" alt="img-product" width="100" class="img-fluid shadow-sm rounded">
                            </td>
                            <td>SKU</td>
                            <td>HARGA BELI</td>
                            <td>HARGA JUAL</td>
                            <td>HARGA RESELLER</td>
                            <td>UKURAN</td>
                            <td>WARNA</td>
                            <td>BERAT</td>
                            <td>STOK</td>
                        </tr>
                        <tr>
                            <td>{{ __('P001V01') }}</td>
                            <td>{{ __('Rp. 80.000') }}</td>
                            <td>{{ __('Rp. 100.000') }}</td>
                            <td>{{ __('Rp. 95.000') }}</td>
                            <td>{{ __('L') }}</td>
                            <td>{{ __('Blue Dark') }}</td>
                            <td>{{ __('10 gr') }}</td>
                            <td>{{ __('29') }}</td>
                        </tr>
                    </table>
                </div>

                <div class="col">
                    <h5 class="card-title my-3">Harga Grosir</h5>
                    <table class="table table-sm table-bordered table-striped grosir">
                        <thead>
                            <th>Rentang</th>
                            <th>Harga Satuan</th>
                        </thead>

                        <tbody>
                            <tr>
                                <td>
                                    <span class="d-inline-block text-right" style="min-width: 20px;">2</span> 
                                    <i class="icon ion-ios-remove ml-1"></i> 
                                    <span class="d-inline-block text-right" style="min-width: 20px;">10</span> 
                                    Produk
                                </td>
                                <td>Rp. 95.000</td>
                            </tr>
                            <tr>
                                <td>
                                    <span class="d-inline-block text-right" style="min-width: 20px;">11</span>  
                                    <i class="icon ion-ios-remove ml-1"></i> 
                                    <span class="d-inline-block text-right" style="min-width: 20px;">20</span> 
                                    Produk
                                </td>
                                <td>Rp. 90.000</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            
            @slot('footer')
                <a href="{{ route('product.index') }}" class="btn btn-md btn-orange">Kembali</a>
            @endslot
        @endcard
    </div>
</div>
@include('components.sweet')
@endsection