Applications/routes/web.php
<?php

Route::get('/', function () {
    return redirect()->route('reseller.shop.get');
});

/* --------- RESELLERS --------- */

// SHOP
Route::get('/', 'Resellers\ShopController@index')->name('reseller.shop.get');
Route::get('/shop', 'Resellers\ShopController@index')->name('reseller.shop.get');
Route::get('/shop/product/{id}', 'Resellers\ShopController@show')->name('reseller.shop.show.get');
Route::get('/shop/search', 'Resellers\ShopController@search')->name('reseller.shop.search.get');
Route::get('/shop/sort', 'Resellers\ShopController@sort')->name('reseller.shop.sort.get');

// AUTH
Route::group(['prefix' => 'reseller', 'middleware' => ['guest']], function () {
    Route::get('/login', 'Resellers\Auth\AuthController@getLogin')->name('reseller.login.get');
	Route::post('/login', 'Resellers\Auth\AuthController@postLogin')->name('reseller.login.post');

	Route::get('/register', 'Resellers\Auth\AuthController@getRegister')->name('reseller.register.get');
	Route::post('/register', 'Resellers\Auth\AuthController@postRegister')->name('reseller.register.post');
});


Route::group(['prefix' => 'reseller'], function() {
	// LOGOUT
	Route::get('/logout', 'Resellers\Auth\AuthController@logout')->name('reseller.logout.get');

	// DASHBOARD
	Route::get('/dashboard', 'Resellers\DashboardController@index')->name('reseller.dashboard.get');

	// ORDERS
	Route::get('/orders', 'Resellers\OrderController@index')->name('reseller.order.get');

	// ADDRESS BILLING
	Route::get('/address/billing', 'Resellers\AddressBillingController@index')->name('reseller.address.billing.get');
	Route::put('/address/billing', 'Resellers\AddressBillingController@update')->name('reseller.address.billing.update');

	// ADDRESS SHIPPING
	Route::get('/address/shipping', 'Resellers\AddressShippingController@index')->name('reseller.address.shipping.get');
	Route::put('/address/shipping', 'Resellers\AddressShippingController@update')->name('reseller.address.shipping.update');

	// DETAIL ACCOUNT
	Route::get('/profile', 'Resellers\ProfileController@index')->name('reseller.profile.get');
	Route::put('/profile', 'Resellers\ProfileController@update')->name('reseller.profile.update');
	Route::put('/profile/change-password', 'Resellers\ProfileController@changePassword')->name('reseller.profile.change.password.update');

	// CART
	Route::post('/cart', 'Resellers\CartController@store')->name('reseller.cart.post');
	Route::post('/cart/delete', 'Resellers\CartController@delete')->name('reseller.cart.delete');

	// CHECKOUT
	Route::get('/checkout', 'Resellers\CheckoutController@index')->name('reseller.checkout.get');
	Route::post('/checkout', 'Resellers\CheckoutController@store')->name('reseller.checkout.post');
	Route::get('/checkout/order-received/{id}', 'Resellers\CheckoutController@orderReceived')->name('reseller.orderReceived.get');
	Route::get('/checkout/konfirmasi-pembayaran/{id}', 'Resellers\CheckoutController@konfirmasiPembayaran')->name('reseller.konfirmasiPembayaran.get');
	Route::post('/checkout/konfirmasi-pembayaran/{id}', 'Resellers\CheckoutController@konfirmasiPembayaranPost')->name('reseller.konfirmasiPembayaran.post');
});


/* --------- ADMIN --------- */
Route::group(['prefix' => 'admin', 'namespace' => 'Auth'], function() {
	// Authentication Routes
	Route::get('/', function () {
		return redirect('admin/login');
	});
	Route::get('/login', 'LoginController@showLoginForm')->name('login');
	Route::post('/login', 'LoginController@login');
	Route::post('/logout', 'LoginController@logout')->name('logout');

	// Registration Routes...
	Route::get('/register', 'RegisterController@showRegistrationForm')->name('register');
	Route::post('/register', 'RegisterController@register');
});

Route::group(['prefix'=>'admin', 'middleware'=> ['auth', 'admin']], function() {
	
	/* --------- Dashboard --------- */
	Route::get('/home', 'HomeController@index')->name('home');

	/* --------- Order / Transaction --------- */
	Route::resource('/order', 'OrderController')->except([
		'show', 'create', 'edit'
	]);
	Route::get('/order/detail/{id}', 'OrderController@show')->name('order.detail');
	Route::get('/order/search', 'OrderController@search')->name('order.search');
	Route::get('/order/new_order', 'OrderController@create')->name('order.new_order');
	Route::get('/order/edit_order/{id}', 'OrderController@edit')->name('order.edit_order');
	Route::get('/order/canceled', 'OrderController@canceled')->name('order.canceled');

	/* --------- Product Management --------- */
	Route::resource('/product', 'ProductController')->except([
		'show', 'create', 'edit'
	]);

	Route::get('/product/detail_product/{id}', 'ProductController@show')->name('product.detail');
	Route::get('/product/add_product', 'ProductController@create')->name('product.create');
	Route::get('/product/{id}/edit_product', 'ProductController@edit')->name('product.edit');
	Route::get('/product/search', 'ProductController@search')->name('product.search');
	Route::get('/product/history/{variant_id}', 'ProductController@history_variant')->name('product.history_variant');
	
	Route::get('/product/category', 'ProductCategoryController@index')->name('product_category.index');
	Route::get('/product/category/{slug}', 'ProductCategoryController@show')->name('product_category.detail');
	Route::get('/product/category/{id}/edit', 'ProductCategoryController@edit')->name('product_category.edit');
	Route::post('/product/category/store', 'ProductCategoryController@store')->name('product_category.store');
	Route::put('/product/category/{id}', 'ProductCategoryController@update')->name('product_category.update');
	Route::delete('/product/category/{id}', 'ProductCategoryController@destroy')->name('product_category.destroy');
	
	Route::get('/product/stock/listdata', 'ProductStockController@listData')->name('product_stock.data');
	Route::get('/product/stock', 'ProductStockController@index')->name('product_stock.index');
	Route::post('/product/stock', 'ProductStockController@store')->name('product_stock.store');
	Route::put('/product/stock/{id}', 'ProductStockController@update')->name('product_stock.update');
	Route::get('/product/stock/{id}/edit', 'ProductStockController@edit')->name('product_stock.edit');
	Route::delete('/product/stock/{id}', 'ProductStockController@destroy')->name('product_stock.destroy');

	Route::get('/product/attribute/listdata', 'ProductAttributeController@listData')->name('product_attribute.data');
	Route::get('/product/attribute', 'ProductAttributeController@index')->name('product_attribute.index');
	Route::post('/product/attribute', 'ProductAttributeController@store')->name('product_attribute.store');
	Route::put('/product/attribute/{id}', 'ProductAttributeController@update')->name('product_attribute.update');
	Route::get('/product/attribute/{id}/edit', 'ProductAttributeController@edit')->name('product_attribute.edit');
	Route::delete('/product/attribute/{id}', 'ProductAttributeController@destroy')->name('product_attribute.destroy');

	/* --------- Customer --------- */
	Route::get('/customer/listdata', 'CustomerController@listData')->name('customer.data');
	Route::resource('/customer', 'CustomerController')->except([
		'show', 'create'
	]);
	Route::get('/customer/search', 'CustomerController@searchCustomer')->name('customer.search');
	// Route::get('/customer/transaction/{id}', 'TransactionController@showCustomerTransaction')->name('customer.transaction');

	/* --------- Supplier --------- */
	Route::get('/supplier/listdata', 'SupplierController@listData')->name('supplier.data');
	Route::resource('/supplier', 'SupplierController')->except([
		'show', 'create'
	]);

	Route::get('/reseller', function() {
	    return 'View Not Found!';
	});

	/* --------- Expense --------- */
	Route::get('/expense/listdata', 'ExpenseController@listdata')->name('expense.data');
	Route::resource('/expense', 'ExpenseController')->except([
		'create'
	]);
	Route::get('/expense/search', 'ExpenseController@search')->name('expense.search');

	/* --------- Report --------- */
	Route::get('/report', 'ReportController@index')->name('report.index');
	Route::get('/report/search', 'ReportController@search')->name('report.search');
	Route::get('/report/detail/{id}', 'ReportController@show')->name('report.detail');

	/* --------- Analyzer --------- */
	Route::get('/analyzer', 'AnalyzerController@index')->name('analyzer.index');
	Route::get('/analyzer/best_seller', 'AnalyzerController@bestSeller')->name('analyzer.best_seller');
	Route::get('/analyzer/best_customer', 'AnalyzerController@bestCustomer')->name('analyzer.best_customer');
	Route::get('/analyzer/best_location', 'AnalyzerController@bestLocation')->name('analyzer.best_location');

	/* --------- Setting --------- */
	Route::get('/setting/general', 'SettingController@index')->name('setting.general');
	Route::get('/setting/supplier', 'SettingController@supplier')->name('setting.supplier');
	Route::get('/setting/user', 'SettingController@user')->name('setting.user');
	Route::get('/setting/sale_target', 'SettingController@saleTarget')->name('setting.sale_target');

	/* --------- Outlet --------- */
	Route::get('setting/general/outlet/{id}/edit', 'OutletController@edit')->name('outlet.edit');
	Route::post('setting/general/outlet', 'OutletController@insert')->name('outlet.insert');
	
	/* --------- User --------- */
	Route::resource('/role', 'RoleController')->except([
        'create', 'show'
    ]);

	/* --------- User --------- */
	Route::get('/user/listdata', 'UserController@listData')->name('user.data');
	Route::resource('/user', 'UserController')->except([
		'index', 'show'
	]);
	Route::get('/user/user_profile', 'UserController@profile')->name('user.profile');
	Route::put('/user/user_profile/{id}', 'UserController@changeProfile')->name('user.update_profile');

	Route::get('/user/roles/{id}', 'UserController@roles')->name('user.roles');
    Route::put('/user/roles/{id}', 'UserController@setRole')->name('user.set_role');

Applications/app/Order.php
<?php

namespace App;

use App\Model;

class Order extends Model
{
    public function reseller()
    {
        return $this->belongsTo(Reseller::class);
    }
}

Applications/app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Order;
use App\Product;
use App\Category;
use App\Stock_management;
use App\Customer;
use App\User;

class OrderController extends Controller
{
    public function index()
    {
        $orders = Order::latest()->get();
    	return view('orders.index', compact('orders'));
    }

    public function show($id)
    {
    	# code...
    }

    public function create()
    {
    	return view('orders.create');
    }

    public function store(Request $request)
    {
    	# code...
    }

    public function update(Order $order,  Request $request)
    {
    	# code...
    }

    public function destroy(Order $order)
    {
    	# code...
    }

    public function canceled()
    {
        # code...
    }
}

Applications/app/Http/Controllers/Resellers/OrderController.php
<?php

namespace App\Http\Controllers\Resellers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Order;

use Auth;

class OrderController extends Controller
{
    public function index()
    {
        $orders = Order::with('reseller')->where('reseller_id', Auth::guard('reseller')->user()->id)->get();
        
        return view('resellers.order.order', compact('orders'));
    }
}

Applications/resources/views/orders/create.blade.php
@extends('layouts.master')

@section('title', 'Order')

@push('css')
    <style>
        .form-control.fc_md, .btn_md { 
            padding: 0.5rem 1rem;
            font-size: 1rem;
            line-height: 1;
        }
        
        .row_header td {
            font-size: .8em;
        }
        .row_content td {
            font-weight: bold;
        }
    </style>
@endpush

@section('breadcrumb')
    @parent
    <li class="breadcrumb-item"><a href="{{ url('/products') }}">Order</a></li>
    <li class="breadcrumb-item active">Tambah</li>
@endsection

@section('main-content')
<div class="row">
    <div class="col-lg-4">
        @card
            <form action="{{ route('product.store') }}" method="post" enctype="multipart/form-data">
                @csrf

                <input type="hidden" name="code" id="code" class="form-control fc_md">
                <div class="form-group">
                    <label for="name">Nama Pemesan</label>
                    <input type="text" name="name" id="name" class="form-control fc_md" required placeholder="Cari Customer">
                </div>
                <div class="form-group">
                    <label for="name">Dikirim Kepada</label>
                    <input type="text" name="name" id="name" class="form-control fc_md" required placeholder="Cari Customer">
                </div>
                <div class="form-group">
                    <label for="name">Dikirim Dari</label>
                    <select name="product_category_id" id="product_category_id" class="form-control fc_md select2" required>
                        <option>-- Pilih Lokasi Pengiriman --</option>
                        <option value="a_to_z">Urutkan A-Z</option>
                        <option value="z_to_a">Urutkan Z-A</option>
                        <option value="lowest">Harga Termurah - Termahal</option>
                        <option value="most_expensive">Harga Termahal - Termurah</option>
                        <option value="smallest">Stok Paling Sedikit</option>
                        <option value="biggest">Stok Paling Banyak</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="name">Tanggal Pesan</label>
                    <input type="text" name="name" id="name" class="form-control fc_md" required>
                </div>
                
                <div class="form-group">
                    <label for="description">Catatan</label>
                    <textarea name="description" id="description" rows="3" class="form-control"></textarea>

                    <input type="checkbox" id="add_print" checked> <label for="add_print" class="font-weight-normal text-sm text-muted">TAMBAHKAN LABEL PRINT</label>
                </div>
            </form>
        @endcard
    </div>

    <div class="col-lg-8">
        <div class="card">
            <div class="card-body">
                <input type="text" class="form-control fc_md" placeholder="Cari Produk..">
            </div>
        </div>

        <div class="card card-border card-orange">
            <div class="card-header">
                <p class="mb-0">ORDERAN</p>
            </div>
            
            <div class="card-body">
                <table width="100%">
                    <tr class="row_header">
                        <td width="40%">NAMA</td>
                        <td width="20%">HARGA</td>
                        <td>QTY</td>
                        <td class="text-center">SUBTOTAL</td>
                    </tr>
                    <tr class="row_content">
                        <td>Mie Goreng</td>
                        <td>Rp. 2.500</td>
                        <td>3</td>
                        <td class="text-right">Rp. 7.500 
                            <a class="text-sm text-muted ml-3" href="{{ __('') }}"><i class="fas fa-ellipsis-h"></i></a>
                        </td>
                    </tr>
                </table>
                <hr>

                <table width="100%">
                    <tr>
                        <td width="40%">Subtotal</td>
                        <td width="20%"></td>
                        <td>
                            <strong>1</strong>
                        </td>
                        <td class="text-right">
                            <strong>Rp. 2.500</strong>
                            <a style="visibility: hidden;" class="text-sm text-muted ml-3" href="{{ __('') }}"><i class="fas fa-ellipsis-h"></i></a>
                        </td>
                    </tr>
                    <tr>
                        <td>Ongkos Kirim 
                            <strong>(0.2 Kg) -</strong>
                        </td>
                        <td></td>
                        <td></td>
                        <td class="text-right">
                            <strong>Rp. 2.000</strong>
                            <a style="visibility: hidden;" class="text-sm text-muted ml-3" href="{{ __('') }}"><i class="fas fa-ellipsis-h"></i></a>
                        </td>
                    </tr>
                </table>

                <div class="row mt-3">
                    <div class="col-12">
                        <button class="btn btn-outline-success"><i class="fas fa-plus-circle"></i> DISKON ORDER</button>
                        <button class="btn btn-outline-success"><i class="fas fa-plus-circle"></i> BIAYA LAIN</button>
                    </div>                
                </div>
                <hr>
                <div class="row mt-3">
                    <div class="col-6">
                        <h5 class="card-title">TOTAL</h5>
                    </div>
                    <div class="col-6 text-right">
                        <h2 class="font-weight-bold">Rp. 2.500</h2>
                    </div>
                </div>
            </div>
        </div>

        <div class="card card-border card-orange">
            <div class="card-header">
                <h5 class="card-title">PEMBAYARAN</h5>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="">Status Pembayaran</label>
                            <select name="" id="" class="form-control fc_md">
                                <option value="">Belum Bayar</option>
                                <option value="">Sudah Bayar (Lunas)</option>
                                <option value="">Cicilan</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="">Bank Pembayaran</label>
                            <select name="" id="" class="form-control fc_md">
                                <option value="">Bank xxxx-xxxx-xxxx</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="">Tanggal Bayar</label>
                            <input type="text" class="form-control fc_md" placeholder="31 Oktober 2019">
                        </div>
                        <div class="form-group">
                            <label for="">Nominal</label>
                            <input type="text" class="form-control fc_md" placeholder="0">
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="card card-border card-orange">
            <div class="card-header">
                <h5 class="card-title">SHIPPING</h5>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-6">
                        <div class="form-group">
                            <label for="">Nomor Resi</label>
                            <input type="text" class="form-control fc_md">
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label for="" style="visibility: hidden;">Please, hide Me.</label>
                            <div class="form-control fc_md">
                                <label for="customSwitch1" class="font-weight-normal d-inline-block mb-1">Kirim SMS <strong>RESI</strong> otomatis</label>
                                <div class="custom-control custom-switch d-inline-block float-right">
                                    <input type="checkbox" class="custom-control-input" id="customSwitch1" checked>
                                    <label class="custom-control-label" for="customSwitch1"></label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@include('components.sweet')
@endsection

@push('scripts')
    <script>
        $(function () {
            $('select').select2()
        })
    </script>
@endpush

Applications/resources/views/orders/edit.blade.php
@extends('layouts.master')

@section('title', 'Edit Produk')

@push('css')
    <link rel="stylesheet" href="{{ asset('/AdminLTE/plugins/summernote/summernote-bs4.css') }}">
    <style>
        .form-control.fc_md, .btn_md { 
            padding: 0.5rem 1rem;
            font-size: 1rem;
            line-height: 1;
        }

        .table label {
            font-size: .7em;
            text-transform: uppercase;
            color: #6c757d;
        }

        .table td {
            border-bottom: 1px solid rgba(0, 0, 0, 0.125);
        }
    </style>
@endpush

@section('breadcrumb')
    @parent
    <li class="breadcrumb-item"><a href="{{ url('/products') }}">Produk</a></li>
    <li class="breadcrumb-item active">Edit</li>
@endsection

@section('main-content')
<div class="row">
    <div class="col-lg-12">
        @card
            <form action="{{ route('product.store') }}" method="post" enctype="multipart/form-data">
                @csrf

                <input type="hidden" name="code" id="code" class="form-control fc_md" required>
                <div class="form-group row">
                    <div class="col-md-8">
                        <label for="name">Nama Produk</label>
                        <input type="text" name="name" id="name" class="form-control fc_md" required>
                    </div>
                    <div class="col-md-4">
                        <label for="product_category_id">Kategori</label>
                        <select name="product_category_id" id="product_category_id" class="form-control fc_md" required>
                            <option>-- Pilih Kategori --</option>
                            @foreach ($product_categories as $category)
                                <option value="{{ $category->id }}">{{ $category->name }}</option>
                            @endforeach
                            <option value="uncategorized">Uncategorized</option>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="description">Deskripsi</label>
                    <textarea name="description" id="description" rows="3" class="form-control"></textarea>
                </div>
                <div class="form-group row">
                    <div class="col-lg-2 col-4">
                        <label for="discount">Diskon</label>
                        <div class="input-group mb-3">
                            <input type="text" class="form-control fc_md" id="discount" name="discount" aria-label="Text input with checkbox">
                            <div class="input-group-append">
                                <div class="input-group-text bg-white">
                                    %
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-8 pl-5">
                        <label for="varian">Kategori Varian</label> 
                        <br>
                        <input type="checkbox" name="size" id="size" checked> <label for="size" class="font-weight-normal mr-3">Ukuran</label>
                        <input type="checkbox" name="color" id="color" checked> <label for="color" class="font-weight-normal">Warna</label>
                    </div>
                </div>
                <table class="table table-sm table-responsive">
                    <thead class="bg-light">
                        <th class="border-left">Foto Produk</th>
                        <th>Spesifikasi</th>
                        <th>Harga Beli</th>
                        <th>Harga Jual</th>
                        <th>Varian</th>
                        <th class="border-right">Stok</th>
                    </thead>

                    <tbody>
                        <td class="border-left">
                            <img src="https://via.placeholder.com/100.png" alt="" class="img-circle mt-1">
                            <input type="file" name="photo" class="form-control form-control-sm mt-1">
                        </td>
                        <td>
                            <div class="form-group">
                                <label for="sku" class="font-weight-normal">SKU</label>
                                <input type="text" class="form-control" name="sku" id="sku">
                            </div>
                            <div class="form-group">
                                <label for="wight" class="font-weight-normal">Berat</label>
                                <input type="text" class="form-control" name="wight" id="wight">
                            </div>
                        </td>
                        <td>
                            <div class="form-group">
                                <label for="purchase_price" style="visibility: hidden;">purchase_price</label>
                                <input type="text" class="form-control" name="purchase_price" id="purchase_price">
                            </div>
                        </td>
                        <td>
                            <div class="form-group">
                                <label for="nominal_price" class="font-weight-normal">Harga Normal</label>
                                <input type="text" class="form-control" name="nominal_price" id="nominal_price">
                            </div>
                            <div class="form-group">
                                <label for="reseller_price" class="font-weight-normal">Harga Reseller</label>
                                <input type="text" class="form-control" name="reseller_price" id="reseller_price">
                            </div>
                        </td>
                        <td>
                            <div class="form-group">
                                <label for="size" class="font-weight-normal">Ukuran</label>
                                <input type="text" class="form-control" name="size" id="size">
                            </div>
                            <div class="form-group">
                                <label for="color" class="font-weight-normal">Warna</label>
                                <input type="text" class="form-control" name="color" id="color">
                            </div>
                        </td>
                        <td class="border-right">
                            <div class="form-group">
                                <label for="stock" style="visibility: hidden;">stock</label>
                                <input type="text" class="form-control" name="stock" id="stock">
                            </div>
                        </td>
                    </tbody>
                </table>
                
                <div class="row">
                <div class="col-lg-7">
                    <div class="form-group">
                        <label for="whosale_price">Harga Grosir</label>
                        <table class="table table-sm">
                            <thead class="bg-light">
                                <th class="border-left">Rentang</th>
                                <th class="border-right">Harga Satuan</th>
                            </thead>
                            <tbody>
                                @for ($i = 0; $i < 5; $i++)
                                    <tr>
                                        <td class="border-left">
                                            <div class="input-group input-group-sm">
                                                <input type="text" class="form-control border-right-0 form-control-sm">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text bg-white" id="">s/d</span>
                                                </div>
                                                <input type="text" class="form-control form-control-sm">
                                            </div>
                                        </td>
                                        <td class="border-right">
                                            <input type="text" class="form-control" name="satuan">
                                        </td>
                                    </tr>
                                @endfor
                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="col-lg-5">
                    <span class="d-block"><strong>Keterangan:</strong></span> 
                    <span class="d-block">Rentang jumlah item dimulai dari 2 (jika kurang tidak bisa digunakan)</span>

                    <br>
                    <span class="d-block"><strong>Contoh:</strong></span>
                    <span class="d-block">Rentang: 2 - 10, Harga: 10000</span> 
                    <span class="d-block">Rentang: 11 - 20, Harga: 9500</span>
                </div>
                </div>
            </form>
            @slot('footer')
                <button class="btn btn-md btn-primary"><i class="fas fa-save"></i> Simpan Poduk</button>
            @endslot
        @endcard
    </div>
</div>
@include('components.sweet')
@endsection

@push('scripts')
    <script src="{{ asset('/AdminLTE/plugins/summernote/summernote-bs4.min.js') }}"></script>
    <script>

        $(function () {
            $('textarea').summernote({
                'height': 150,
            })

            $('span:not(.brand-text)').addClass('text-muted')

            $('select').select2()
            $('[type=checkbox]').prop('indeterminate', true)
        })
    </script>
@endpush