Applications/routes/web.php
Route::get('/shop', 'Resellers\ShopController@index')->name('reseller.shop.get');
Route::get('/shop/product/{id}', 'Resellers\ShopController@show')->name('reseller.shop.show.get');
Route::get('/shop/search', 'Resellers\ShopController@search')->name('reseller.shop.search.get');
Route::get('/shop/sort', 'Resellers\ShopController@sort')->name('reseller.shop.sort.get');

// AUTH
Route::group(['prefix' => 'reseller', 'middleware' => ['guest']], function () {
    Route::get('/login', 'Resellers\Auth\AuthController@getLogin')->name('reseller.login.get');
	Route::post('/login', 'Resellers\Auth\AuthController@postLogin')->name('reseller.login.post');

	Route::get('/register', 'Resellers\Auth\AuthController@getRegister')->name('reseller.register.get');
	Route::post('/register', 'Resellers\Auth\AuthController@postRegister')->name('reseller.register.post');
});


Route::group(['prefix' => 'reseller'], function() {
	// LOGOUT
	Route::get('/logout', 'Resellers\Auth\AuthController@logout')->name('reseller.logout.get');

	// DASHBOARD
	Route::get('/dashboard', 'Resellers\DashboardController@index')->name('reseller.dashboard.get');

	// ORDERS
	Route::get('/orders', 'Resellers\OrderController@index')->name('reseller.order.get');

	// ADDRESS BILLING
	Route::get('/address/billing', 'Resellers\AddressBillingController@index')->name('reseller.address.billing.get');
	Route::put('/address/billing', 'Resellers\AddressBillingController@update')->name('reseller.address.billing.update');

	// ADDRESS SHIPPING
	Route::get('/address/shipping', 'Resellers\AddressShippingController@index')->name('reseller.address.shipping.get');
	Route::put('/address/shipping', 'Resellers\AddressShippingController@update')->name('reseller.address.shipping.update');

	// DETAIL ACCOUNT
	Route::get('/profile', 'Resellers\ProfileController@index')->name('reseller.profile.get');
	Route::put('/profile', 'Resellers\ProfileController@update')->name('reseller.profile.update');
	Route::put('/profile/change-password', 'Resellers\ProfileController@changePassword')->name('reseller.profile.change.password.update');

	// CART
	Route::post('/cart', 'Resellers\CartController@store')->name('reseller.cart.post');
	Route::post('/cart/delete', 'Resellers\CartController@delete')->name('reseller.cart.delete');

	// CHECKOUT
	Route::get('/checkout', 'Resellers\CheckoutController@index')->name('reseller.checkout.get');
	Route::post('/checkout', 'Resellers\CheckoutController@store')->name('reseller.checkout.post');
	Route::get('/checkout/order-received/{id}', 'Resellers\CheckoutController@orderReceived')->name('reseller.orderReceived.get');
	Route::get('/checkout/konfirmasi-pembayaran/{id}', 'Resellers\CheckoutController@konfirmasiPembayaran')->name('reseller.konfirmasiPembayaran.get');
	Route::post('/checkout/konfirmasi-pembayaran/{id}', 'Resellers\CheckoutController@konfirmasiPembayaranPost')->name('reseller.konfirmasiPembayaran.post');
});


/* --------- ADMIN --------- */
Route::group(['prefix' => 'admin', 'namespace' => 'Auth'], function() {
	// Authentication Routes
	Route::get('/', function () {
		return redirect('admin/login');
	});
	Route::get('/login', 'LoginController@showLoginForm')->name('login');
	Route::post('/login', 'LoginController@login');
	Route::post('/logout', 'LoginController@logout')->name('logout');

	// Registration Routes...
	Route::get('/register', 'RegisterController@showRegistrationForm')->name('register');
	Route::post('/register', 'RegisterController@register');
});

Route::group(['prefix'=>'admin', 'middleware'=> ['auth', 'admin']], function() {
	
	/* --------- Dashboard --------- */
	Route::get('/home', 'HomeController@index')->name('home');

	/* --------- Order / Transaction --------- */
	Route::resource('/order', 'OrderController')->except([
		'show', 'create', 'edit'
	]);
	Route::get('/order/detail/{id}', 'OrderController@show')->name('order.detail');
	Route::get('/order/search', 'OrderController@search')->name('order.search');
	Route::get('/order/new_order', 'OrderController@create')->name('order.new_order');
	Route::get('/order/edit_order/{id}', 'OrderController@edit')->name('order.edit_order');
	Route::get('/order/canceled', 'OrderController@canceled')->name('order.canceled');

	/* --------- Product Management --------- */
	Route::resource('/product', 'ProductController')->except([
		'show', 'create', 'edit'
	]);

	Route::get('/product/detail_product/{id}', 'ProductController@show')->name('product.detail');
	Route::get('/product/add_product', 'ProductController@create')->name('product.create');
	Route::get('/product/{id}/edit_product', 'ProductController@edit')->name('product.edit');
	Route::get('/product/search', 'ProductController@search')->name('product.search');
	Route::get('/product/history/{variant_id}', 'ProductController@history_variant')->name('product.history_variant');
	
	Route::get('/product/category', 'ProductCategoryController@index')->name('product_category.index');
	Route::get('/product/category/{slug}', 'ProductCategoryController@show')->name('product_category.detail');
	Route::get('/product/category/{id}/edit', 'ProductCategoryController@edit')->name('product_category.edit');
	Route::post('/product/category/store', 'ProductCategoryController@store')->name('product_category.store');
	Route::put('/product/category/{id}', 'ProductCategoryController@update')->name('product_category.update');
	Route::delete('/product/category/{id}', 'ProductCategoryController@destroy')->name('product_category.destroy');
	
	Route::get('/product/stock/listdata', 'ProductStockController@listData')->name('product_stock.data');
	Route::get('/product/stock', 'ProductStockController@index')->name('product_stock.index');
	Route::post('/product/stock', 'ProductStockController@store')->name('product_stock.store');
	Route::put('/product/stock/{id}', 'ProductStockController@update')->name('product_stock.update');
	Route::get('/product/stock/{id}/edit', 'ProductStockController@edit')->name('product_stock.edit');
	Route::delete('/product/stock/{id}', 'ProductStockController@destroy')->name('product_stock.destroy');

	Route::get('/product/attribute/listdata', 'ProductAttributeController@listData')->name('product_attribute.data');
	Route::get('/product/attribute', 'ProductAttributeController@index')->name('product_attribute.index');
	Route::post('/product/attribute', 'ProductAttributeController@store')->name('product_attribute.store');
	Route::put('/product/attribute/{id}', 'ProductAttributeController@update')->name('product_attribute.update');
	Route::get('/product/attribute/{id}/edit', 'ProductAttributeController@edit')->name('product_attribute.edit');
	Route::delete('/product/attribute/{id}', 'ProductAttributeController@destroy')->name('product_attribute.destroy');

	/* --------- Customer --------- */
	Route::get('/customer/listdata', 'CustomerController@listData')->name('customer.data');
	Route::resource('/customer', 'CustomerController')->except([
		'show', 'create'
	]);
	Route::get('/customer/search', 'CustomerController@searchCustomer')->name('customer.search');
	// Route::get('/customer/transaction/{id}', 'TransactionController@showCustomerTransaction')->name('customer.transaction');

	/* --------- Supplier --------- */
	Route::get('/supplier/listdata', 'SupplierController@listData')->name('supplier.data');
	Route::resource('/supplier', 'SupplierController')->except([
		'show', 'create'
	]);

	Route::get('/reseller', function() {
	    return 'View Not Found!';
	});

	/* --------- Expense --------- */
	Route::get('/expense/listdata', 'ExpenseController@listdata')->name('expense.data');
	Route::resource('/expense', 'ExpenseController')->except([
		'create'
	]);
	Route::get('/expense/search', 'ExpenseController@search')->name('expense.search');

	/* --------- Report --------- */
	Route::get('/report', 'ReportController@index')->name('report.index');
	Route::get('/report/search', 'ReportController@search')->name('report.search');
	Route::get('/report/detail/{id}', 'ReportController@show')->name('report.detail');

	/* --------- Analyzer --------- */
	Route::get('/analyzer', 'AnalyzerController@index')->name('analyzer.index');
	Route::get('/analyzer/best_seller', 'AnalyzerController@bestSeller')->name('analyzer.best_seller');
	Route::get('/analyzer/best_customer', 'AnalyzerController@bestCustomer')->name('analyzer.best_customer');
	Route::get('/analyzer/best_location', 'AnalyzerController@bestLocation')->name('analyzer.best_location');

	/* --------- Setting --------- */
	Route::get('/setting/general', 'SettingController@index')->name('setting.general');
	Route::get('/setting/supplier', 'SettingController@supplier')->name('setting.supplier');
	Route::get('/setting/user', 'SettingController@user')->name('setting.user');
	Route::get('/setting/sale_target', 'SettingController@saleTarget')->name('setting.sale_target');

	/* --------- Outlet --------- */
	Route::get('setting/general/outlet/{id}/edit', 'OutletController@edit')->name('outlet.edit');
	Route::post('setting/general/outlet', 'OutletController@insert')->name('outlet.insert');
	
	/* --------- User --------- */
	Route::resource('/role', 'RoleController')->except([
        'create', 'show'
    ]);

	/* --------- User --------- */
	Route::get('/user/listdata', 'UserController@listData')->name('user.data');
	Route::resource('/user', 'UserController')->except([
		'index', 'show'
	]);
	Route::get('/user/user_profile', 'UserController@profile')->name('user.profile');
	Route::put('/user/user_profile/{id}', 'UserController@changeProfile')->name('user.update_profile');

	Route::get('/user/roles/{id}', 'UserController@roles')->name('user.roles');
    Route::put('/user/roles/{id}', 'UserController@setRole')->name('user.set_role');
    Route::post('/user/permission', 'UserController@addPermission')->name('user.add_permission');
    Route::get('/user/role_permission', 'UserController@rolePermission')->name('user.roles_permission');

Applications/app/Supplier.php
<?php

namespace App;

use App\Model;

class Supplier extends Model
{
    //
}

Applications/app/Http/Controllers/SupplierController.php
<?php

namespace App\Http\Controllers;

use App\Supplier;
use Illuminate\Http\Request;

class SupplierController extends Controller
{
    public function index()
    {
        return view('suppliers.index');
    }

    public function listData()
    {
        $supplier = Supplier::latest()->get();
        $no = 0;
        $data = array();

        foreach ($supplier as $list) {
            $no++;
            $row = array();
            $row[] = $no;
            $row[] = $list->name;
            $row[] = $list->delivery_location;
            $row[] = $list->phone;
            $row[] = $list->address;
            $row[] = '
                    <a href="#" onclick="edit('. $list->id .')" class="btn btn-link"><i class="fas fa-pencil-alt"></i></a>
                    <a href="#" onclick="_delete('. $list->id .')" class="btn btn-link text-danger"><i class="fas fa-trash-alt"></i></a>
            ';
            $data[] = $row;
        }

        $output = ['data' => $data];
        return response()->json($output);
    }

    public function store(Request $request)
    {
        $supplier = Supplier::create([
            'name' => $request->name,
            'delivery_location' => $request->delivery_location,
            'phone' => $request->phone,
            'address' => $request->address,
            'description' => $request->description
        ]);

        return response()->json([
            'message' => 'Supplier berhasil ditambahkan.'
        ]);
    }

    public function edit(Supplier $supplier)
    {
        echo json_encode($supplier);
    }

    public function update(Request $request, Supplier $supplier)
    {
        $supplier->update([
            'name' => $request->name,
            'delivery_location' => $request->delivery_location,
            'phone' => $request->phone,
            'address' => $request->address,
            'description' => $request->description
        ]);

        return response()->json([
            'message' => 'Supplier berhasil diubah.'
        ]);
    }

    public function destroy(Supplier $supplier)
    {
        $supplier->delete();
        return response()->json([
            'message' => 'Data supplier berhasil dihapus.'
        ]);
    }
}

Applications/resources/views/suppliers/form.blade.php
@modal
    @slot('title', '')
    
    <form method="post" class="needs-validation" novalidate>
        @csrf @method('post')
        <input type="hidden" name="id" id="id">
		
		<div class="form-group">
            <div class="col-md-4">
                <label for="name" class="col-form-label">Nama Supplier</label>
                <input type="text" name="name" id="name" class="form-control" required>
                <div class="invalid-feedback">
                    Isi nama supplier.
                </div>
            </div>
            <div class="col-md-4">
                <label for="delivery_location" class="col-form-label">Lokasi Pengiriman</label>
                <input type="text" name="delivery_location" id="delivery_location" class="form-control" required>
                <div class="invalid-feedback">
                    Isi lokasi pengiriman.
                </div>
            </div>
            <div class="col-md-4">
                <label for="phone" class="col-form-label">HP / No Telpon</label>
                <input type="number" name="phone" id="phone" class="form-control" required>
                <div class="invalid-feedback">
                    Isi HP / No Telpon.
                </div>
            </div>
        </div>
		
		<div class="form-group">
            <div class="col-md-12">
                <label for="address" class="col-form-label">Alamat</label>
                <textarea name="address" id="address" class="form-control">-</textarea>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12">
                <label for="description" class="col-form-label">Keterangan / Catatan</label>
                <textarea name="description" id="description" class="form-control">-</textarea>
            </div>
        </div>

        <div class="footer float-right">
            <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
@endmodal

@push('scripts')
    <script>
        $('.form-group').addClass('row')
    </script>
@endpush

Applications/resources/views/suppliers/index.blade.php
@extends('layouts.master')

@section('title', 'Supplier')

@section('breadcrumb')
    @parent
    <li class="breadcrumb-item active">Supplier</li>
@endsection

@section('main-content')
<div class="row">
    <div class="col-md-12">
    	@card
			@slot('title')
                <a href="#" class="btn btn-primary btn-sm" onclick="add()"><i class="fa fa-plus-circle"></i> Tambah</a>
            @endslot

            @table
                @slot('thead')
	                <th width="30">No</th>
	                <th>Nama Supplier</th>
	                <th>Lokasi Pengiriman</th>
	                <th>No Telpon</th>
	                <th>Alamat</th>
	                <th width="100">Aksi</th>
			    @endslot
			@endtable
		@endcard
	</div>
</div>
@include('suppliers.form')
@endsection

@push('scripts')
<script src="{{ asset('/js/sweet.js') }}"></script>
<script src="{{ asset('/js/validate.js') }}"></script>
<script>
	let table, save_method;
	$(function() {
		table = $('.table').DataTable({
			'processing' : true,
			'autoWidth' : false,
			'ajax' : {
				'url' : '{{ route('supplier.data') }}',
				'type' : 'GET'
			}
		});
	})

	$(function() {
		$('#modal-form').validator().on('submit', function(e) {
			if(!e.preventDefault()) {
				let id = $('#id').val();
				
				if(save_method == 'add') url = '{{ route('supplier.store') }}';
				else url = 'supplier/' + id;

				$.ajax({
					url : url,
					type : 'POST',
					data : $('#modal-form form').serialize(),
					success : function(data) {
						$('#modal-form').modal('hide');
						table.ajax.reload();

						_swall(data.message);
					}
				})

				return false;
			}
		})
	})

	function add() {
		save_method = 'add';
		$('.needs-validation').removeClass('was-validated')
        $("#modal-form").modal({
            backdrop: 'static',
            keyboard: false
        });
		$('#modal-form').modal('show');
		$('input[name=_method]').val('POST');
		$('#modal-form form')[0].reset();
		$('.modal-title').text('Tambah Supplier');
	}

	function edit(id) {
		save_method = 'edit';
		$('.needs-validation').removeClass('was-validated')
        $("#modal-form").modal({
            backdrop: 'static',
            keyboard: false
        });
		$('input[name=_method]').val('PATCH');
		$('#modal-form form')[0].reset();

		$.ajax({
			url : 'supplier/' + id + '/edit',
			type : 'GET',
			dataType : 'JSON',
			success : function(data) {
				$('#modal-form').modal('show');
				$('.modal-title').text('Edit Supplier');

				$('#id').val(data.id);
				$('#name').val(data.name);
				$('#delivery_location').val(data.delivery_location);
				$('#phone').val(data.phone);
				$('#address').val(data.address);
				$('#description').val(data.description);
			}, 
			error : function() {
				alert('Tidak dapat menampilkan data');
			}
		})
	}

	function _delete(id) {
		if(confirm('Apakah yakin data akan dihapus?')) {
			$.ajax({
				url : 'supplier/' + id,
				type : 'POST',
				data : {'_method' : 'DELETE', '_token' : $('meta[name=csrf-token]').attr('content')},
				success : function(data) {
					table.ajax.reload();
					_swall(data.message);
				},
				error : function() {
					alert('Tidak dapat menghapus data!');
				}
			})
		}
	}
</script>
@endpush