Applications/routes/web.php
Route::get('/shop', 'Resellers\ShopController@index')->name('reseller.shop.get');
Route::get('/shop/product/{id}', 'Resellers\ShopController@show')->name('reseller.shop.show.get');
Route::get('/shop/search', 'Resellers\ShopController@search')->name('reseller.shop.search.get');
Route::get('/shop/sort', 'Resellers\ShopController@sort')->name('reseller.shop.sort.get');

// AUTH
Route::group(['prefix' => 'reseller', 'middleware' => ['guest']], function () {
    Route::get('/login', 'Resellers\Auth\AuthController@getLogin')->name('reseller.login.get');
	Route::post('/login', 'Resellers\Auth\AuthController@postLogin')->name('reseller.login.post');

	Route::get('/register', 'Resellers\Auth\AuthController@getRegister')->name('reseller.register.get');
	Route::post('/register', 'Resellers\Auth\AuthController@postRegister')->name('reseller.register.post');
});


Route::group(['prefix' => 'reseller'], function() {
	// LOGOUT
	Route::get('/logout', 'Resellers\Auth\AuthController@logout')->name('reseller.logout.get');

	// DASHBOARD
	Route::get('/dashboard', 'Resellers\DashboardController@index')->name('reseller.dashboard.get');

	// ORDERS
	Route::get('/orders', 'Resellers\OrderController@index')->name('reseller.order.get');

	// ADDRESS BILLING
	Route::get('/address/billing', 'Resellers\AddressBillingController@index')->name('reseller.address.billing.get');
	Route::put('/address/billing', 'Resellers\AddressBillingController@update')->name('reseller.address.billing.update');

	// ADDRESS SHIPPING
	Route::get('/address/shipping', 'Resellers\AddressShippingController@index')->name('reseller.address.shipping.get');
	Route::put('/address/shipping', 'Resellers\AddressShippingController@update')->name('reseller.address.shipping.update');

	// DETAIL ACCOUNT
	Route::get('/profile', 'Resellers\ProfileController@index')->name('reseller.profile.get');
	Route::put('/profile', 'Resellers\ProfileController@update')->name('reseller.profile.update');
	Route::put('/profile/change-password', 'Resellers\ProfileController@changePassword')->name('reseller.profile.change.password.update');

	// CART
	Route::post('/cart', 'Resellers\CartController@store')->name('reseller.cart.post');
	Route::post('/cart/delete', 'Resellers\CartController@delete')->name('reseller.cart.delete');

	// CHECKOUT
	Route::get('/checkout', 'Resellers\CheckoutController@index')->name('reseller.checkout.get');
	Route::post('/checkout', 'Resellers\CheckoutController@store')->name('reseller.checkout.post');
	Route::get('/checkout/order-received/{id}', 'Resellers\CheckoutController@orderReceived')->name('reseller.orderReceived.get');
	Route::get('/checkout/konfirmasi-pembayaran/{id}', 'Resellers\CheckoutController@konfirmasiPembayaran')->name('reseller.konfirmasiPembayaran.get');
	Route::post('/checkout/konfirmasi-pembayaran/{id}', 'Resellers\CheckoutController@konfirmasiPembayaranPost')->name('reseller.konfirmasiPembayaran.post');
});


/* --------- ADMIN --------- */
Route::group(['prefix' => 'admin', 'namespace' => 'Auth'], function() {
	// Authentication Routes
	Route::get('/', function () {
		return redirect('admin/login');
	});
	Route::get('/login', 'LoginController@showLoginForm')->name('login');
	Route::post('/login', 'LoginController@login');
	Route::post('/logout', 'LoginController@logout')->name('logout');

	// Registration Routes...
	Route::get('/register', 'RegisterController@showRegistrationForm')->name('register');
	Route::post('/register', 'RegisterController@register');
});

Route::group(['prefix'=>'admin', 'middleware'=> ['auth', 'admin']], function() {
	
	/* --------- Dashboard --------- */
	Route::get('/home', 'HomeController@index')->name('home');

	/* --------- Order / Transaction --------- */
	Route::resource('/order', 'OrderController')->except([
		'show', 'create', 'edit'
	]);
	Route::get('/order/detail/{id}', 'OrderController@show')->name('order.detail');
	Route::get('/order/search', 'OrderController@search')->name('order.search');
	Route::get('/order/new_order', 'OrderController@create')->name('order.new_order');
	Route::get('/order/edit_order/{id}', 'OrderController@edit')->name('order.edit_order');
	Route::get('/order/canceled', 'OrderController@canceled')->name('order.canceled');

	/* --------- Product Management --------- */
	Route::resource('/product', 'ProductController')->except([
		'show', 'create', 'edit'
	]);

	Route::get('/product/detail_product/{id}', 'ProductController@show')->name('product.detail');
	Route::get('/product/add_product', 'ProductController@create')->name('product.create');
	Route::get('/product/{id}/edit_product', 'ProductController@edit')->name('product.edit');
	Route::get('/product/search', 'ProductController@search')->name('product.search');
	Route::get('/product/history/{variant_id}', 'ProductController@history_variant')->name('product.history_variant');
	
	Route::get('/product/category', 'ProductCategoryController@index')->name('product_category.index');
	Route::get('/product/category/{slug}', 'ProductCategoryController@show')->name('product_category.detail');
	Route::get('/product/category/{id}/edit', 'ProductCategoryController@edit')->name('product_category.edit');
	Route::post('/product/category/store', 'ProductCategoryController@store')->name('product_category.store');
	Route::put('/product/category/{id}', 'ProductCategoryController@update')->name('product_category.update');
	Route::delete('/product/category/{id}', 'ProductCategoryController@destroy')->name('product_category.destroy');
	
	Route::get('/product/stock/listdata', 'ProductStockController@listData')->name('product_stock.data');
	Route::get('/product/stock', 'ProductStockController@index')->name('product_stock.index');
	Route::post('/product/stock', 'ProductStockController@store')->name('product_stock.store');
	Route::put('/product/stock/{id}', 'ProductStockController@update')->name('product_stock.update');
	Route::get('/product/stock/{id}/edit', 'ProductStockController@edit')->name('product_stock.edit');
	Route::delete('/product/stock/{id}', 'ProductStockController@destroy')->name('product_stock.destroy');

	Route::get('/product/attribute/listdata', 'ProductAttributeController@listData')->name('product_attribute.data');
	Route::get('/product/attribute', 'ProductAttributeController@index')->name('product_attribute.index');
	Route::post('/product/attribute', 'ProductAttributeController@store')->name('product_attribute.store');
	Route::put('/product/attribute/{id}', 'ProductAttributeController@update')->name('product_attribute.update');
	Route::get('/product/attribute/{id}/edit', 'ProductAttributeController@edit')->name('product_attribute.edit');
	Route::delete('/product/attribute/{id}', 'ProductAttributeController@destroy')->name('product_attribute.destroy');

	/* --------- Customer --------- */
	Route::get('/customer/listdata', 'CustomerController@listData')->name('customer.data');
	Route::resource('/customer', 'CustomerController')->except([
		'show', 'create'
	]);
	Route::get('/customer/search', 'CustomerController@searchCustomer')->name('customer.search');
	// Route::get('/customer/transaction/{id}', 'TransactionController@showCustomerTransaction')->name('customer.transaction');

	/* --------- Supplier --------- */
	Route::get('/supplier/listdata', 'SupplierController@listData')->name('supplier.data');
	Route::resource('/supplier', 'SupplierController')->except([
		'show', 'create'
	]);

	Route::get('/reseller', function() {
	    return 'View Not Found!';
	});

	/* --------- Expense --------- */
	Route::get('/expense/listdata', 'ExpenseController@listdata')->name('expense.data');
	Route::resource('/expense', 'ExpenseController')->except([
		'create'
	]);
	Route::get('/expense/search', 'ExpenseController@search')->name('expense.search');

	/* --------- Report --------- */
	Route::get('/report', 'ReportController@index')->name('report.index');
	Route::get('/report/search', 'ReportController@search')->name('report.search');
	Route::get('/report/detail/{id}', 'ReportController@show')->name('report.detail');

	/* --------- Analyzer --------- */
	Route::get('/analyzer', 'AnalyzerController@index')->name('analyzer.index');
	Route::get('/analyzer/best_seller', 'AnalyzerController@bestSeller')->name('analyzer.best_seller');
	Route::get('/analyzer/best_customer', 'AnalyzerController@bestCustomer')->name('analyzer.best_customer');
	Route::get('/analyzer/best_location', 'AnalyzerController@bestLocation')->name('analyzer.best_location');

	/* --------- Setting --------- */
	Route::get('/setting/general', 'SettingController@index')->name('setting.general');
	Route::get('/setting/supplier', 'SettingController@supplier')->name('setting.supplier');
	Route::get('/setting/user', 'SettingController@user')->name('setting.user');
	Route::get('/setting/sale_target', 'SettingController@saleTarget')->name('setting.sale_target');

	/* --------- Outlet --------- */
	Route::get('setting/general/outlet/{id}/edit', 'OutletController@edit')->name('outlet.edit');
	Route::post('setting/general/outlet', 'OutletController@insert')->name('outlet.insert');
	
	/* --------- User --------- */
	Route::resource('/role', 'RoleController')->except([
        'create', 'show'
    ]);

	/* --------- User --------- */
	Route::get('/user/listdata', 'UserController@listData')->name('user.data');
	Route::resource('/user', 'UserController')->except([
		'index', 'show'
	]);
	Route::get('/user/user_profile', 'UserController@profile')->name('user.profile');
	Route::put('/user/user_profile/{id}', 'UserController@changeProfile')->name('user.update_profile');

	Route::get('/user/roles/{id}', 'UserController@roles')->name('user.roles');
    Route::put('/user/roles/{id}', 'UserController@setRole')->name('user.set_role');
    Route::post('/user/permission', 'UserController@addPermission')->name('user.add_permission');
    Route::get('/user/role_permission', 'UserController@rolePermission')->name('user.roles_permission');

Applications/app/Role.php
<?php

namespace App;

use App\Model;

class Role extends Model
{
    //
}

Applications/app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Role;

class RoleController extends Controller
{
    public function index()
    {
        $roles = Role::orderBy('created_at', 'DESC')->paginate(10);
        return view('roles.index', compact('roles'));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string|max:50'
        ]);

        $role = Role::firstOrCreate(['name' => $request->name]);
        return back()->with('message', [
            'title' => 'Role berhasil ditambahkan.'
        ]);
    }

    public function edit(Role $role)
    {
        echo json_encode($role);
    }

    public function update(Role $role, Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string|max:50'
        ]);

        $role->update(['name' => $request->name]);
        return back()->with('message', [
            'title' => 'Role berhasil diubah.'
        ]);
    }

    public function destroy(Role $role)
    {
        $role->delete();
        return back()->with('message', [
            'title' => 'Role berhasil dihapus.'
        ]);
    }
}

Applications/resources/views/roles/index.blade.php
@extends('layouts.master')

@section('title', 'Manajemen Role')

@section('breadcrumb')
    @parent
    <li class="breadcrumb-item"><a href="{{ route('setting.user') }}">User</a></li>
    <li class="breadcrumb-item active">Manajemen Role</li>
@endsection

@section('main-content')
<div class="row">
    <div class="col-md-4">
        @card
            @slot('card_id', 'card_form')
            @slot('title')
                <h5 class="card-title">Tambah</h5>
                <div class="card-tools">
                    <a href="#" class="btn btn-link text-secondary" onclick="add()" title="Tambah Baru"><i class="fas fa-plus-circle"></i></a>
                </div>
            @endslot

            <form role="form" action="{{ route('role.store') }}" method="post" class="needs-validation" novalidate>
                @csrf @method('post')
                <input type="hidden" name="id">
                <div class="form-group">
                    <label for="name">Role</label>
                    <input type="text" name="name" class="form-control" id="name" required>
                    <div class="invalid-feedback">
                        Masukan Role yang ingin ditambahkan.
                    </div>
                </div>
                <button class="btn btn-primary">Simpan</button>
            </form>
        @endcard
    </div>

    <div class="col-md-8">
        @card
            @slot('title')
                <h5 class="card-title">List Role</h5>
            @endslot
            
            @table
                @slot('thead')
                    <tr>
                        <th>#</th>
                        <th width="50%">Role</th>
                        <th>Created At</th>
                        <th>Aksi</th>
                    </tr>
                @endslot
                
                @php $no = 1; @endphp
                @foreach ($roles as $role)
                <tr>
                    <td>{{ $no++ }}</td>
                    <td>{{ $role->name }}</td>
                    <td>{{ date('d/m/Y', strtotime($role->created_at)) }}</td>
                    <td>
                        <a href="#" onclick="edit('{{ $role->id }}')" class="btn btn-link btn-sm"><i class="fa fa-pencil-alt"></i></a>
                        <form action="{{ route('role.destroy', $role->id) }}" method="post" class="d-inline-block">
                            @csrf
                            <input type="hidden" name="_method" value="DELETE">
                            <button type="submit" class="btn btn-link btn-sm text-danger" onclick="return confirm('Are you sure?')"><i class="fa fa-trash-alt"></i></button>
                        </form>
                    </td>
                </tr>
                @endforeach
            @endtable        
        @endcard
    </div>
</div>
@include('components.sweet')
@endsection


@push('scripts')
<script src="{{ asset('/js/validate.js') }}"></script>
<script>
    let table = $('.table').DataTable({
        "autoWidth" : false,
        "language": {
          "emptyTable": "Ups data masih kosong!.",
          "zeroRecords": "Ups data tidak ditemukan!."
        }
    })

    function edit(id) {
        $('#card_form .card-title').text('Edit Role');
        $('#card_form form').attr('action', '{{ url('admin/role') }}' +'/'+ id)[0].reset();
        $('input[name=_method]').val('put');

        $.ajax({
            url : '{{ url('admin/role') }}' +'/'+ id + '/edit',
            type : 'get',
            dataType : 'json',
            success : function(data) {
                $('input[name=id]').val(data.id);
                $('input[name=name]').val(data.name).focus();
            }
        })
    }

    function add() {
        $('#card_form .card-title').text('Tambah');
        $('#card_form form').attr('action', '{{ url('admin/role') }}')[0].reset();
        $('input[name=_method]').val('post');
        $('input[name=name]').focus();
    }
</script>
@endpush